# Generated by Django 6.0.3 on 2026-03-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.PositiveIntegerField(default=3)),
                ('tipo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao_processo', models.TextField()),
                ('decisoes_tomadas', models.TextField(blank=True)),
                ('erros_encontrados', models.TextField(blank=True)),
                ('correcoes_realizadas', models.TextField(blank=True)),
                ('justificacao_modelacao', models.TextField(blank=True)),
                ('uso_ia', models.TextField(blank=True)),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('pagina_pessoal', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('ects', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ucs/')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaMakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ficheiro', models.FileField(upload_to='makingof/evidencias/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('making_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='portfolio.makingof')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_uc', to='portfolio.anoletivo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_uc', to='portfolio.curso')),
                ('docentes', models.ManyToManyField(blank=True, related_name='ofertas_uc', to='portfolio.professor')),
                ('unidade_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='portfolio.unidadecurricular')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao_curta', models.CharField(max_length=255)),
                ('descricao_longa', models.TextField()),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='projetos/capas/')),
                ('tipo', models.CharField(choices=[('academico', 'Académico'), ('pessoal', 'Pessoal'), ('profissional', 'Profissional'), ('freelance', 'Freelance'), ('outro', 'Outro')], max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('repositorio', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planeado', 'Planeado'), ('em_desenvolvimento', 'Em desenvolvimento'), ('em_producao', 'Em produção'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], max_length=25)),
                ('objetivo', models.TextField()),
                ('video_demo', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('papel', models.CharField(max_length=150)),
                ('conceitos_aplicados', models.TextField(blank=True)),
                ('areas', models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.area')),
                ('competencias', models.ManyToManyField(blank=True, related_name='projetos_relacionados', to='portfolio.competencia')),
                ('oferta_uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='portfolio.ofertauc')),
                ('palavras_chave', models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.palavrachave')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='projetos/imagens/')),
                ('legenda', models.CharField(blank=True, max_length=150)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outras_imagens', to='portfolio.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('linguagem', 'Linguagem'), ('framework', 'Framework'), ('bd', 'Base de Dados'), ('ferramenta', 'Ferramenta'), ('outro', 'Outro')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tecnologias/')),
                ('website_oficial', models.URLField(blank=True, null=True)),
                ('nivel_interesse', models.PositiveIntegerField(default=3)),
                ('competencias', models.ManyToManyField(blank=True, related_name='tecnologias_relacionadas', to='portfolio.competencia')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.tecnologia'),
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('entidade', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('certificado', models.URLField(blank=True, null=True)),
                ('competencias', models.ManyToManyField(blank=True, related_name='formacoes', to='portfolio.competencia')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='formacoes', to='portfolio.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(default='TFC', max_length=50)),
                ('resumo', models.TextField()),
                ('link_relatorio', models.URLField(blank=True, null=True)),
                ('alunos', models.ManyToManyField(related_name='tfcs', to='portfolio.aluno')),
                ('ano_letivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tfcs', to='portfolio.anoletivo')),
                ('areas', models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.area')),
                ('cursos', models.ManyToManyField(related_name='tfcs', to='portfolio.curso')),
                ('orientadores', models.ManyToManyField(blank=True, related_name='tfcs_orientados', to='portfolio.professor')),
                ('palavras_chave', models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.palavrachave')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.tecnologia')),
            ],
        ),
    ]
