# Generated by Django 6.0.3 on 2026-03-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_anoletivo_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao_processo', models.TextField()),
                ('decisoes_tomadas', models.TextField(blank=True)),
                ('erros_encontrados', models.TextField(blank=True)),
                ('correcoes_realizadas', models.TextField(blank=True)),
                ('justificacao_modelacao', models.TextField(blank=True)),
                ('uso_ia', models.TextField(blank=True)),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaMakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ficheiro', models.FileField(upload_to='makingof/evidencias/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('making_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='portfolio.makingof')),
            ],
        ),
    ]
