# Generated by Django 6.0.3 on 2026-03-26 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_makingof_evidenciamakingof'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('ects', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ucs/')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_uc', to='portfolio.anoletivo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_uc', to='portfolio.curso')),
                ('docentes', models.ManyToManyField(blank=True, related_name='ofertas_uc', to='portfolio.professor')),
                ('unidade_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='portfolio.unidadecurricular')),
            ],
        ),
    ]
