# Generated by Django 6.0.3 on 2026-03-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_unidadecurricular_ofertauc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('linguagem', 'Linguagem'), ('framework', 'Framework'), ('bd', 'Base de Dados'), ('ferramenta', 'Ferramenta'), ('outro', 'Outro')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tecnologias/')),
                ('website_oficial', models.URLField(blank=True, null=True)),
                ('nivel_interesse', models.PositiveIntegerField(default=3)),
            ],
        ),
    ]
