# Generated by Django 6.0.3 on 2026-03-26 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_area_palavrachave_tecnologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(default='TFC', max_length=50)),
                ('resumo', models.TextField()),
                ('link_relatorio', models.URLField(blank=True, null=True)),
                ('alunos', models.ManyToManyField(related_name='tfcs', to='portfolio.aluno')),
                ('ano_letivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tfcs', to='portfolio.anoletivo')),
                ('areas', models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.area')),
                ('cursos', models.ManyToManyField(related_name='tfcs', to='portfolio.curso')),
                ('orientadores', models.ManyToManyField(blank=True, related_name='tfcs_orientados', to='portfolio.professor')),
                ('palavras_chave', models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.palavrachave')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.tecnologia')),
            ],
        ),
    ]
