# Generated by Django 6.0.3 on 2026-03-26 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_aluno_tfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao_curta', models.CharField(max_length=255)),
                ('descricao_longa', models.TextField()),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='projetos/capas/')),
                ('tipo', models.CharField(choices=[('academico', 'Académico'), ('pessoal', 'Pessoal'), ('profissional', 'Profissional'), ('freelance', 'Freelance'), ('outro', 'Outro')], max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('repositorio', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planeado', 'Planeado'), ('em_desenvolvimento', 'Em desenvolvimento'), ('em_producao', 'Em produção'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], max_length=25)),
                ('objetivo', models.TextField()),
                ('video_demo', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('papel', models.CharField(max_length=150)),
                ('conceitos_aplicados', models.TextField(blank=True)),
                ('oferta_uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='portfolio.ofertauc')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='projetos/imagens/')),
                ('legenda', models.CharField(blank=True, max_length=150)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outras_imagens', to='portfolio.projeto')),
            ],
        ),
    ]
