# Generated by Django 6.0.3 on 2026-03-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projeto_imagemprojeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.PositiveIntegerField(default=3)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('projetos', models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.projeto')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('entidade', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('certificado', models.URLField(blank=True, null=True)),
                ('competencias', models.ManyToManyField(blank=True, related_name='formacoes', to='portfolio.competencia')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='formacoes', to='portfolio.tecnologia')),
            ],
        ),
    ]
